using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace JRK.JevRunner.SourceGenerators;

/// <summary>
/// Produces request construction and answer accessor source code for validated query mappings.
/// </summary>
internal static class JevQuerySourceCodeGenerator
{
    /// <summary>
    /// Reopens namespaces and generic containing classes and emits documented ordinary methods.
    /// </summary>
    /// <param name="type">The validated query type whose namespace and partial declaration are generated.</param>
    /// <param name="containers">The containing declarations, ordered from outermost to the query itself.</param>
    /// <param name="questions">The validated question mappings, in request construction and answer accessor order.</param>
    /// <returns>The complete partial query declaration as C# source text.</returns>
    internal static string GenerateSourceCode(INamedTypeSymbol type, IReadOnlyCollection<INamedTypeSymbol> containers,
        IReadOnlyList<QuestionMapping> questions)
    {
        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        AppendNamespaceDeclaration(source, type.ContainingNamespace);
        AppendContainingDeclarations(source, containers);

        var localNames = new HashSet<string>(containers.SelectMany(container => container.TypeParameters)
            .Select(parameter => parameter.Name), StringComparer.Ordinal);
        AppendRequestMethod(source, questions, localNames);
        AppendAnswerAccessors(source, questions, localNames);

        foreach (var _ in containers)
            source.AppendLine("}");
        if (!type.ContainingNamespace.IsGlobalNamespace)
            source.AppendLine("}");
        return source.ToString();
    }

    /// <summary>
    /// Opens the query's namespace using escaped names, unless it is the global namespace.
    /// </summary>
    /// <remarks>
    /// For example: <c>namespace @MyApp.@Queries {</c>.
    /// </remarks>
    private static void AppendNamespaceDeclaration(StringBuilder source, INamespaceSymbol namespaceSymbol)
    {
        if (!namespaceSymbol.IsGlobalNamespace)
        {
            var parts = new Stack<string>();
            for (var current = namespaceSymbol; !current.IsGlobalNamespace; current = current.ContainingNamespace)
                parts.Push(Identifier(current.Name));
            source.AppendLine($"namespace {string.Join(".", parts)} {{");
        }
    }

    /// <summary>
    /// Opens partial containing types and the query in their supplied outermost-first order.
    /// </summary>
    /// <remarks>
    /// For example: <c>partial class @Container&lt;@T&gt; { partial class @Query {</c>.
    /// </remarks>
    private static void AppendContainingDeclarations(StringBuilder source,
        IReadOnlyCollection<INamedTypeSymbol> containers)
    {
        foreach (var container in containers)
        {
            source.Append(container.IsStatic ? "static " : string.Empty).Append("partial ")
                .Append(container.IsRecord ? "record class " : "class ").Append(Identifier(container.Name));
            if (container.TypeParameters.Length != 0)
                source.Append('<')
                    .Append(string.Join(", ", container.TypeParameters.Select(parameter => Identifier(parameter.Name))))
                    .Append('>');
            source.AppendLine(" {");
        }
    }

    /// <summary>
    /// Emits request construction and adds each configured question in mapping order.
    /// </summary>
    /// <remarks>
    /// For example: <c>public Request GetRequest() { var request = new Request(this.State, this.JevModel); ... return request; }</c>.
    /// </remarks>
    private static void AppendRequestMethod(StringBuilder source, IReadOnlyList<QuestionMapping> questions,
        HashSet<string> localNames)
    {
        var request = LocalName("request", localNames);
        source.AppendLine(
            "/// <summary>Creates a request from this query's state, model, instructions, and ordered question configuration.</summary>");
        source.AppendLine("/// <returns>A new request containing each interface-defined question.</returns>");
        source.AppendLine("public global::JRK.JevRunner.Request GetRequest() {");
        source.AppendLine($"var {request} = new global::JRK.JevRunner.Request(this.@State, this.@JevModel);");

        for (var index = 0; index < questions.Count; index++)
            AppendQuestion(source, questions[index], index, request, localNames);

        source.AppendLine($"return {request};\n}}");
    }

    /// <summary>
    /// Reads a question through its definition interface, configures its builder, and adds it to the request.
    /// </summary>
    /// <remarks>
    /// For example: <c>var definition = (IQuestionDefinition)this.Budget; var builder = new QuestionBuilder(nameof(this.Budget), definition.Instructions); ... RequestExtensions.AddQuestion(request, builder);</c>.
    /// </remarks>
    private static void AppendQuestion(StringBuilder source, QuestionMapping question, int index, string request,
        HashSet<string> localNames)
    {
        var property = Identifier(question.Property.Name);
        var definition = LocalName("__jevDefinition" + index, localNames);
        var interfaceType = question.Interface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        source.AppendLine($"var {definition} = ({interfaceType})this.{property};");

        var builder = LocalName("__jevQuestion" + index, localNames);
        var builderType = question.Builder.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        source.AppendLine($"var {builder} = new {builderType}(nameof(this.{property}), {definition}.@Instructions);");

        if (question.Configuration == ConfigurationKind.Noul)
            AppendNoulConfiguration(source, definition, builder, index, localNames);
        else
            AppendCollectionConfiguration(source, question.Configuration, definition, builder, index, localNames);

        source.AppendLine($"global::JRK.JevRunner.Requests.RequestExtensions.AddQuestion({request}, {builder});");
    }

    /// <summary>
    /// Emits yes/no configuration only when both optional criteria are present.
    /// </summary>
    /// <remarks>
    /// For example: <c>var yes = definition.Yes; var no = definition.No; if (yes != null &amp;&amp; no != null) { builder.AddYesNo(yes, no); }</c>.
    /// </remarks>
    private static void AppendNoulConfiguration(StringBuilder source, string definition, string builder, int index,
        HashSet<string> localNames)
    {
        var yes = LocalName("__jevYes" + index, localNames);
        var no = LocalName("__jevNo" + index, localNames);
        source.AppendLine($"var {yes} = {definition}.@Yes;")
            .AppendLine($"var {no} = {definition}.@No;")
            .AppendLine($"if ({yes} != null && {no} != null) {{")
            .AppendLine($"{builder}.@AddYesNo({yes}, {no});")
            .AppendLine("}");
    }

    /// <summary>
    /// Emits ordered choice or score configuration using the definition's enumerable contract.
    /// </summary>
    /// <remarks>
    /// For choices: <c>IEnumerable&lt;ChoiceCriteria&gt; items = definition.Choices; foreach (var item in items) { builder.AddChoice(item.Choice, item.Instruction); }</c>.
    /// For scores: <c>IEnumerable&lt;string&gt; items = definition.Criterias; foreach (var item in items) { builder.AddCriteria(item); }</c>.
    /// </remarks>
    private static void AppendCollectionConfiguration(StringBuilder source, ConfigurationKind configuration,
        string definition, string builder, int index, HashSet<string> localNames)
    {
        var items = LocalName("__jevItems" + index, localNames);
        var item = LocalName("__jevItem" + index, localNames);
        var isChoice = configuration == ConfigurationKind.Choice;
        var itemType = isChoice ? "global::JRK.JevRunner.Requests.ChoiceCriteria" : "global::System.String";
        var property = isChoice ? "@Choices" : "@Criterias";

        source.AppendLine($"global::System.Collections.Generic.IEnumerable<{itemType}> {items} = {definition}.{property};");
        source.AppendLine($"foreach (var {item} in {items}) {{");
        var addItem = isChoice
            ? $"{builder}.@AddChoice({item}.@Choice, {item}.@Instruction);"
            : $"{builder}.@AddCriteria({item});";
        source.AppendLine(addItem + "\n}");
    }

    /// <summary>
    /// Emits a named, typed response lookup method for every validated question mapping.
    /// </summary>
    /// <remarks>
    /// For example: <c>public NoulAnswer GetBudgetAnswer(Response response) { return response.GetRequiredNoulAnswer(nameof(this.Budget)); }</c>.
    /// </remarks>
    private static void AppendAnswerAccessors(StringBuilder source, IReadOnlyList<QuestionMapping> questions,
        HashSet<string> localNames)
    {
        var response = LocalName("response", localNames);
        foreach (var question in questions)
        {
            var answerType = question.Answer.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var method = Identifier("Get" + question.Property.Name + "Answer");
            var accessor = Identifier(question.Accessor);
            var property = Identifier(question.Property.Name);

            source.AppendLine(
                "/// <summary>Returns the required typed answer for this query's named question.</summary>")
                .AppendLine($"/// <param name=\"{response}\">The response containing the named answer.</param>")
                .AppendLine("/// <returns>The answer; the response lookup throws if it is missing or has another type.</returns>")
                .AppendLine($"public {answerType} {method}(global::JRK.JevRunner.Response {response}) {{")
                .AppendLine($"return {response}.{accessor}(nameof(this.{property}));\n}}");
        }
    }

    /// <summary>
    /// Escapes an identifier so names that match C# keywords remain valid in generated source.
    /// </summary>
    /// <remarks>
    /// For example: <c>class</c> becomes <c>@class</c>.
    /// </remarks>
    private static string Identifier(string name) => "@" + name;

    /// <summary>
    /// Allocates a generated local or parameter name without shadowing containing type parameters.
    /// </summary>
    /// <remarks>
    /// For example: if <c>request</c> is already reserved, returns <c>request_</c> and reserves it for subsequent allocations.
    /// </remarks>
    private static string LocalName(string preferred, HashSet<string> names)
    {
        var name = preferred;
        while (!names.Add(name))
            name += "_";
        return name;
    }
}
