<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>

        <RootNamespace>JRK.JevRunner.SourceGenerators</RootNamespace>
        <PackageId>JRK.JevRunner.SourceGenerators</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <!-- CSharp supplies a matching Microsoft.CodeAnalysis.Analyzers dependency. -->
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" PrivateAssets="all" />
        <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
        <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
    </ItemGroup>


</Project>
